name: Github Secrets

on:
    workflow_dispatch:

jobs:
    print_secret_values:
        runs-on: windows-latest
        steps:
            - name: Print secret values
              run: |
                echo "MY_Secret value is : ${{ secrets.TOP_SECRET_KEY }}"
                echo "I am not exists is : ${{ secrets.I_AM_NOT_EXISTS }}"
            - name: Print secret value as environment variables
              run: |
                    echo "MY_Secret value is : $TOP_SECRET_KEY "
              env:
                    TOP_SECRET_KEY : ${{ secrets.TOP_SECRET_KEY }}