name: Environment Variables

on:
    workflow_dispatch:

env:
    Day_of_the_week: Monday
    testvar: value-1
    TOP_SECRET_KEY: i-am-a-top-secret-key

jobs:
    mainjob:
        name: "print the environment variables"
        runs-on: macos-latest

        env:
            Greeting: Dear
            testvar: value-2

        steps:
            - name: print-the-env-variables-value
              run: |
                  echo "Hello $Greeting $name. Today is $Day_of_the_week"
                  echo " testvar $testvar"
                  echo "testvar ${{env.testvar}}"

            #   env:
            #       name: Dharshini
            #       testvar: value-3
