name: Print some Environment variables

on:
    workflow_dispatch:

jobs:
    print_some_environment_variables:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Some Default Environment Variables"
                echo "-----------------------------------"
                echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
                echo "GITHUB_PATH: $GITHUB_PATH"
                echo "GITHUB_ACTION: $GITHUB_ACTION"
                echo "GITHUB_API_URL: $GITHUB_API_URL"
                echo "GITHUB_ACTOR: $GITHUB_ACTOR"
                echo "GITHUB_SERVER_URL: $GITHUB_SERVER_URL"
                echo "GITHUB_REPOSITORY_OWNER: $GITHUB_REPOSITORY_OWNER"
                echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
                echo "GITHUB_ENV: $GITHUB_ENV"
                echo "GITHUB_JOB: $GITHUB_JOB"
                echo "GITHUB_STEP_SUMMARY: $GITHUB_STEP_SUMMARY"
                echo "RUNNER_NAME: $GITHUB_SERVER_URL"
                echo "RUNNER_NAME: $RUNNER_NAME"
                echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"