name: Set Environment variables

on:
    workflow_dispatch:

jobs:
    custom_github_env_variable:
        runs-on: macos-latest
        steps:
            - name: set the value
              id: step_01
              run: |
                  echo "action_status=yellow" >> $GITHUB_ENV
            - name: use the value
              id: step_02
              run: |
                  echo "${{env.action_status}}"
